language: node_js
node_js:
  - "8"
sudo: required
script:
  - |
    (for dir in $(find $PWD -maxdepth 2 -name package.json -printf "%h\n"); do
      cd $dir && npm install && npm test && npm run lint || exit 1
    done)
branches:
  only:
  - master
notifications:
  email: false
